apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- patches/auth-replica-patch.yaml
- patches/cart-replica-patch.yaml
- patches/frontend-replica-patch.yaml
- patches/payments-replica-patch.yaml
- patches/product-replica-patch.yaml
resources:
- ../../base/auth
- ../../base/cart
- ../../base/frontend
- ../../base/payments
- ../../base/product
images:
- name: akhilthyadi/kube-auth
  newName: akhilthyadi/kube-auth
  newTag: v8
