apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5001
  type: {{ .Values.service.type }}

