adminUser: admin
adminPassword: admin123

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

dashboards:
  default:
    node-dashboard:
      file: /var/lib/grafana/dashboards/node-dashboard.json
    pod-dashboard:
      file: /var/lib/grafana/dashboards/pod-dashboard.json
    custom-kube-shop-dashboard:
      file: /var/lib/grafana/dashboards/custom-kube-shop-dashboard.json

extraVolumeMounts:
  - name: dashboards
    mountPath: /var/lib/grafana/dashboards

extraVolumes:
  - name: dashboards
    configMap:
      name: grafana-dashboards

