apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 7000
          envFrom:
            - configMapRef:
                name: payments-config
            - secretRef:
                name: payments-secret

