apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 7000
  type: {{ .Values.service.type }}

