apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-app
  namespace: argocd
spec:
  destination:
    namespace: cart
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/akhil27051999/Cloud-native-E-commerce-Platform-named-kubeshop.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/dev
    kustomize:
      namePrefix: cart-
      patches:
        - path: patches/cart-replica-patch.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

