apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-app
  namespace: argocd
spec:
  destination:
    namespace: product
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/akhil27051999/Cloud-native-E-commerce-Platform-named-kubeshop.git
    targetRevision: main
    path: k8s-manifests/overlays/dev
    kustomize:
      namePrefix: product-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
